title: "Carlos A. Duran Villalobos Portfolio"
description: "A comprehensive portfolio showcasing projects in machine learning, data analysis, and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
theme: minima
