title: "Carlos A. Duran Villalobos Portfolio"
description: "A comprehensive portfolio showcasing projects in machine learning, data analysis, and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carlosaduranvillalobos.github.io/" # the base hostname & protocol for your site
theme: minima

# Navigation menu
nav:
  - title: "Home"
    url: "/"
  - title: "Machine Learning & AI "
    url: "/machine-learning"
  - title: "Data Analysis & Viz"
    url: "/data-visualization"
  - title: "Cloud & Big Data"
    url: "/cloud-computing/"
  - title: "Bioinformatics"
    url: "/bioinformatics/"
  - title: "Process Control"
    url: "/control-systems"
  - title: "About"
  #  url: "/about"
    url: "/#about"
