title: "Carlos Alberto Duran Villalobos Portfolio"
description: "A comprehensive portfolio showcasing projects in machine learning, data analysis, and more."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://carlosaduranvillalobos.github.io/" # the base hostname & protocol for your site
theme: minima

# Navigation menu
nav:
  - title: "Home"
    url: "/"
  - title: "Machine Learning and AI Projects"
    url: "/machine-learning/"
  - title: "Data Visualization and Analysis"
    url: "/data-visualization/"
  - title: "Cloud Computing and Big Data"
    url: "/cloud-computing/"
  - title: "Bioinformatics Projects"
    url: "/bioinformatics/"
  - title: "Control Systems and Process Optimization"
    url: "/control-systems/"

